### ISSUE TITLE
Example UI to "play" with the API

### ISSUE THREAD

**Issue by vidas** [aifoundry-org/NekkoAPI#6]
It would be great to have a UI with which users could test out the API server (even though it will be mostly accessed through the code). The main goal is to have something up and running in seconds. The barrier to entry should be as low as possible. Something as low effort as running `make demo`.

(Other uses - actual demos and testing/debugging stuff by developers).

1. Please research open source LLM Web UI tools (like [Chat UI](https://github.com/huggingface/chat-ui) by HuggingFace or [Open WebUI](https://docs.openwebui.com/).
  - selected UI **must** use OpenAI API and have configurable URL
  - selected UI **must** use `/v1/chat/completions` API endpoint (most use legacy and low-level `/v1/completions`)
  - it **should** be possible (preferably via user interface) to tweak various parameters, like `max_tokens`, `temperature`, `top_n` and so on.
2. Please share your findings.
3. Create a script in the examples folder/makefile target to run the preconfigured UI (container) alongside our example NekkoAPI server container.

**Comment by akxcv** [comment]
Open WebUI satisfies all the listed requirements and is quite easy to set up. Posted a demo implementation in #12.

One downside I found is poor control over playground features: there's no way to disable speech recognition or other capabilities that our server does not yet support. Though I don't think that's a big deal, since our goal is to implement full compatibility with OpenAI API. Also, it won't be difficult to switch our UI to something else down the line if needed.
